# Generated by Django 3.0.4 on 2020-03-12 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('venue', models.TextField()),
                ('date', models.DateField(blank=True, null=True)),
                ('time', models.CharField(max_length=10)),
                ('details', models.TextField()),
                ('details_html', models.TextField(blank=True)),
                ('cover_pic', models.ImageField(blank=True, default='/static/defaults/ecell.png', null=True, upload_to='static/uploads/events/cover')),
                ('icon', models.ImageField(default='static/defaults/ecell.png', upload_to='static/uploads/events/icon')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('flag', models.BooleanField(default=False)),
                ('year', models.IntegerField(default=2019)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
